Update main.tf
terraform-community-modules/tf_aws_rds pull request #15
Opened 2017-05-05 05:08 UTC by deepakagrawal2

2017-05-05 06:03 UTC, gstlt commented on main.tf
> +        "Name" = "Test"
Quotes around "Name" are not needed.
Also: How this is useful? Maybe use ${var.database_name} or something?

2017-06-23 22:37 UTC, ghost requested changes

2017-06-23 22:37 UTC, kamilboratynski commented on main.tf
> +        "Name" = "Test"
@gstlt Same comment here, this tag does not provide any value.
@deepakagrawal2 Are you going to parameterize `Name` tag?

2017-08-24 19:29 UTC, af6140 commented
Mos likely just an accident with git operation.

2017-08-24 19:32 UTC, closed without merging

2017-08-24 19:33 UTC, antonbabenko commented
This PR does not bring anything new, so I closed it.